version: 2

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  apt_packages:
    - git-lfs
  tools:
    python: "3.10"
  jobs:
    post_system_dependencies:
      - git lfs pull

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - "doc"
